spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: alert
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
          model: gemini-2.5-flash

server:
  port: ${SERVER_PORT:10419}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}

time:
  format: yyyy-MM-dd HH:mm:ss
  zone-id: Asia/Seoul

zipkin:
  base-url: https://zipkin.iunot.cloud